prj1 <- read.csv("household_power_consumption.txt", header = TRUE, sep = ";", quote = "\"", dec = ".", fill = TRUE, comment.char = "")
prj1$Date <- as.Date(prj1$Date, format='%d/%m/%Y')
finalData <-  prj1[prj1$Date %in%  as.Date(c('2007-02-01','2007-02-02')), ]
finalData$datetime <- as.POSIXlt(paste(finalData$Date,finalData$Time))
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(finalData$datetime, as.numeric(as.character(finalData$Global_active_power)), type="l", xlab = "", ylab="Global Active Power")
plot(finalData$datetime, as.numeric(as.character(finalData$Voltage)), type="l", xlab = "datetime", ylab="Voltage")
plot(finalData$datetime, as.numeric(as.character(finalData$Sub_metering_1)), type="l", xlab = "", ylab="Energy sub metering")
lines(finalData$datetime, as.numeric(as.character(finalData$Sub_metering_2)), type="l", col = "red")
lines(finalData$datetime, as.numeric(as.character(finalData$Sub_metering_3)), type="l", col = "blue")
legend("topright",cex=0.7, lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(finalData$datetime, as.numeric(as.character(finalData$Global_reactive_power)), type="l", xlab = "datetime", ylab="Global_reactive_power")
dev.off()